// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Roughcut.DataMartServices.Core.Interfaces;

namespace Roughcut.DataMartServices.Infrastructure.DbModels
{
    public partial class DimDateTime : IDimDateTime
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long DimDateTimeKeyId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime DateTimeCalendarKey { get; set; }

        public short DayNumberOfWeek { get; set; }

        [Required]
        [StringLength(10)]
        public string EnglishDayNameOfWeek { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime CreateDateTime { get; set; } = DateTime.Now;

        [Column(TypeName = "datetime")]
        public DateTime LastChangeDateTime { get; set; } = DateTime.Now;
    }
}